### ISSUE TITLE
systemui崩溃

### ISSUE THREAD

**Issue by ghost** [capntrips/KernelFlasher#10]
在打开Kernel Flasher时，我的systemui崩溃。
[ 2023-04-12T06:31:07.279    10060:  3881:  4351 E/AndroidRuntime  ] FATAL EXCEPTION: wmshell.splashscreen
Process: com.android.systemui, PID: 3881
java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityTaskManager$Stub$Proxy.onSplashScreenViewCopyFinished(IActivityTaskManager.java:3992)
	at android.app.ActivityTaskManager.onSplashScreenViewCopyFinished(ActivityTaskManager.java:218)
	at com.android.wm.shell.startingsurface.StartingSurfaceDrawer.copySplashScreenView(StartingSurfaceDrawer.java:550)
	at com.android.wm.shell.startingsurface.StartingWindowController.lambda$copySplashScreenView$1(StartingWindowController.java:175)
	at com.android.wm.shell.startingsurface.StartingWindowController.$r8$lambda$Nsve7j-qdEujmRJ49hHw0qVTWtY(Unknown Source:0)
	at com.android.wm.shell.startingsurface.StartingWindowController$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:374)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.view.SurfaceControl.-$$Nest$mcheckNotReleased(Unknown Source:0)
	at android.view.SurfaceControl$Transaction.checkPreconditions(SurfaceControl.java:2981)
	at android.view.SurfaceControl$Transaction.setPosition(SurfaceControl.java:3149)
	at com.android.server.wm.TaskOrganizerController.applyStartingWindowAnimation(TaskOrganizerController.java:492)
	at com.android.server.wm.ActivityRecord.onCopySplashScreenFinish(ActivityRecord.java:2791)

**Comment by capntrips** [comment]
Unless there's some incompatibly with Kernel Flasher's splash screen, I don't see anything related to Kernel Flasher in that stack trace. Can you attach a log file with more context?

I assume the app crashed before ever loading the UI? Can you provide some details about the app, device, and OS (versions, etc)?

**Comment by capntrips** [comment]
I see it gets force stopped, but I'm not seeing any obvious causes. I don't know anything about KernelSU, but assuming it provides a similar interface to Magisk, can you ensure Kernel Flasher is allowed root access?

Does any part of the UI load? Again, can you provide some detail of your set up (app version, device, OS version, KernelSU version)? Assuming you're using `v1.0.0-alpha14`, can you confirm that `v1.0.0-alpha13` is also affected?

**Comment by capntrips** [comment]
I tried both stock (`d0c93842`) and alpha (`709f25f6`) Magisk 26101, but I'm unable to replicate the issue on a Pixel 6a. I'm not seeing anything obvious causes from looking through your logs. My only suggestion at this point is to maybe try to build the run it from source in Android Studio, and maybe it will provide more interesting feedback (or at least more isolated logs in the Logcat tool window with `package:mine`).

**Comment by Xynonners** [comment]
Also encountering a similar issue, magisk 26.2, SM-X900 (Tab S8 Ultra). Crashes on app startup, no UI is loaded.

The provided +deps apk is also "invalid" according to installer.

**Comment by capntrips** [comment]
Do you have anything interesting in your logcat when it crashes?

**Comment by Xynonners** [comment]
One thing to note also is that on my device, armabi-v7a apks crash for some reason.

**Comment by Xynonners** [comment]
there's also this part (grep'd for kernel)
```
09-15 05:44:50.048  6446  6446 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=8c6abb5c-7b69-4488-895e-f172503e8b16 flg=0x400010 pkg=com.github.capntrips.kernelflasher (has extras) } in com.topjohnwu.superuser.internal.RootServiceManager$ServiceReceiver@a61f553
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.ui.screens.main.MainViewModel.<init>(MainViewModel.kt:59)
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.MainActivity$onAidlConnected$2$1.invoke(MainActivity.kt:170)
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.MainActivity$onAidlConnected$2$1.invoke(MainActivity.kt:168)
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.MainActivity$onAidlConnected$2.invoke(MainActivity.kt:317)
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.MainActivity$onAidlConnected$2.invoke(MainActivity.kt:166)
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.MainActivity.onAidlConnected(MainActivity.kt:166)
09-15 05:44:50.048  6446  6446 E AndroidRuntime:        at com.github.capntrips.kernelflasher.MainActivity$AidlConnection.onServiceConnected(MainActivity.kt:75)
09-15 05:44:50.050  3190 21788 W ActivityManager: crash : com.github.capntrips.kernelflasher,10392
09-15 05:44:50.051  3190 21788 W ActivityTaskManager:   Force finishing activity com.github.capntrips.kernelflasher/.MainActivity
09-15 05:44:50.051  3190 21788 D ActivityTaskManager: scheduleTopResumedActivityChanged, onTop=false r=ActivityRecord{859f13 u0 com.github.capntrips.kernelf
```

**Comment by Xynonners** [comment]
and also these 3 lines:

```
09-15 05:44:49.735  6491  6491 D com.github.capntrips.kernelflasher:root: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
09-15 05:44:49.735  6491  6491 D com.github.capntrips.kernelflasher:root: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
09-15 05:44:49.741  6491  6491 W ziparchive: Unable to open '/data/user_de/0/com.github.capntrips.kernelflasher/cache/main.dm': No such file or directory
```

**Comment by capntrips** [comment]
Give `v1.0.0-alpha15` a try.  I'm not seeing anything obvious in the logs, but the full stack traces and a bit more context around them might be helpful if the issue persists.
